apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: check-notification-gateway
  namespace: notification
spec:
  selector:
    istio: ingressgateway-notification # use custom Istio gateway implementation
  servers:
  - port:
      number: 82
      name: http
      protocol: HTTP
    hosts:
    - "*"